# Generated by Django 5.2.4 on 2025-07-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('mensaje', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reloj',
            old_name='nombre',
            new_name='marca',
        ),
        migrations.AddField(
            model_name='reloj',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reloj',
            name='modelo',
            field=models.CharField(default='Genérico', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reloj',
            name='precio_oficial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reloj',
            name='precio_retail',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
